version: 2
jobs:
  build_docker_image:
    working_directory: /tmp/build
    docker:
      - image: circleci/build-image
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: push
          command: |
            TAG=$CIRCLE_BUILD_NUM
            docker -v
            docker build -t spareroom/ghost-google-cloud:$TAG -t spareroom/ghost-google-cloud:latest .
            docker images
            docker login -u $DOCKER_USER -p $DOCKER_PASS -e $DOCKER_EMAIL
            docker push spareroom/ghost-google-cloud:$TAG
            docker push spareroom/ghost-google-cloud:latest
workflows:
  version: 2
  build:
    jobs:
      - build_docker_image:
          context: org-global
