version: 2
jobs:
  build_docker_image:
    working_directory: /tmp/build
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          command: docker build -t spareroom/ghost-google-cloud:v1-$CIRCLE_BUILD_NUM .
      - run:
          name: push
          command: |
            docker -v
            docker login --username $DOCKER_USER --password $DOCKER_PASS
            docker push spareroom/ghost-google-cloud:v1-$CIRCLE_BUILD_NUM
workflows:
  version: 2
  build:
    jobs:
      - build_docker_image:
          context: org-global
