version: 2
jobs:
  build_docker_image:
    working_directory: /tmp/build
    docker:
      - image: circleci/build-image
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          command: docker build -t spareroom/ghost-google-cloud:$CIRCLE_BUILD_NUM -t spareroom/ghost-google-cloud:latest .
      - push:
          name: push
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push spareroom/ghost-google-cloud:$CIRCLE_BUILD_NUM
            docker push spareroom/ghost-google-cloud:latest

workflows:
  version: 2
  build:
    jobs:
      - build_docker_image:
          context: org-global
