apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: spareroom/ghost-google-cloud:36
        ports:
        - containerPort: 2368
        imagePullPolicy: Always
        env:
        - name: GHOST_DB
          value: "blog"
        - name: GHOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: spareroomussqldb
              key: password
        - name: GHOST_USER
          valueFrom:
            secretKeyRef:
              name: spareroomussqldb
              key: username
        - name: GHOST_DB_HOST
          value: "127.0.0.1"
      - image: gcr.io/cloudsql-docker/gce-proxy:1.09
        name: cloudsql-proxy
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=api-project-274440984329:europe-west2:ghost=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: ssl-certs
            mountPath: /etc/ssl/certs
          - name: cloudsql
            mountPath: /cloudsql
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName:
                spareroomussql
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
