apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: spareroom/ghost-google-cloud:22
        ports:
        - containerPort: 2368
        imagePullPolicy: Always
      imagePullSecrets:
        - name: spareroomdockercredentials
